### ISSUE TITLE
[PE-D] Unclear instruction for find command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-4/tp#145]
The instruction does not explain if `NAME` is required if `*` is not used and whether `NAME` should be the first keyword that follows `find` in that case.

For e.g. what happens if I enter `find Hardware`?

![image.png](https://raw.githubusercontent.com/honganhcs/ped/main/files/aa80ca82-e8b5-452e-b164-51040e8a031d.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: honganhcs/ped#2

**Comment by zhongfu** [comment]
`find Hardware` will obviously find all the employees named 'Hardware', but this is also a good point because we use square brackets to denote optional args

and we can't really differentiate between different types of optional positional args

should probably use some other way to indicate that it's a required arg (but you can use * for it). maybe parentheses instead of sq brackets?
